// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk--wjszXbL4iPeF1ixRdMLplnBmtDMGw',
    appId: '1:502894037216:web:6e43d1b4e1140428946885',
    messagingSenderId: '502894037216',
    projectId: 'bro-car-631ce',
    authDomain: 'bro-car-631ce.firebaseapp.com',
    storageBucket: 'bro-car-631ce.appspot.com',
    measurementId: 'G-00TYC5RT70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDel7WbPRe_7hOpUgBltXMr55XaYyG_9wc',
    appId: '1:502894037216:android:55f9db8aa0fb556a946885',
    messagingSenderId: '502894037216',
    projectId: 'bro-car-631ce',
    storageBucket: 'bro-car-631ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-oeK3_hE11jTQ7fbFHMZJ3O4I_JM84Lc',
    appId: '1:502894037216:ios:3f7b6b9509c651eb946885',
    messagingSenderId: '502894037216',
    projectId: 'bro-car-631ce',
    storageBucket: 'bro-car-631ce.appspot.com',
    iosClientId: '502894037216-d1jc67cida522gtquid08jf479tmvli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-oeK3_hE11jTQ7fbFHMZJ3O4I_JM84Lc',
    appId: '1:502894037216:ios:3f7b6b9509c651eb946885',
    messagingSenderId: '502894037216',
    projectId: 'bro-car-631ce',
    storageBucket: 'bro-car-631ce.appspot.com',
    iosClientId: '502894037216-d1jc67cida522gtquid08jf479tmvli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk--wjszXbL4iPeF1ixRdMLplnBmtDMGw',
    appId: '1:502894037216:web:b0f2e968478add5b946885',
    messagingSenderId: '502894037216',
    projectId: 'bro-car-631ce',
    authDomain: 'bro-car-631ce.firebaseapp.com',
    storageBucket: 'bro-car-631ce.appspot.com',
    measurementId: 'G-N4P1814816',
  );

}